eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8761/eureka/
server:
    port: 8765
spring:
    application:
        name: service-order
feign:
    hystrix:
       enabled: true